[build]
  publish = "."

[build.processing]
  skip_processing = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/fecca"
  to = "/fecca.html"
  status = 200